# Generated by Django 4.0.4 on 2022-04-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_alter_catagories_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagories',
            name='description',
            field=models.CharField(default='description', max_length=100),
        ),
    ]
