# Generated by Django 4.0.4 on 2022-04-27 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0006_subcat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCat',
        ),
    ]
